language: node_js
node_js:
  - "6"
before_script:
 - export TZ=America/Los_Angeles
script:
  - npm run build
  - npm run codecov
  - npm run test:ui -- --max-old-space-size=8192
  - npm run lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache: yarn
notifications:
  email: never
  slack:
    rooms:
      - vega-js:qSRohErJJQzUfQTlBv4hivUl
    on_success: change
    on_failure: change
cache:
  directories:
  - $HOME/.yarn-cache
